import React from "react";
import { useRouter } from "next/router";
import { signOut, useSession } from "next-auth/react";

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {ImagesBlock} from "../components/imageBlock";


export default function Home() {
  const { data, status } = useSession();
  const router = useRouter();

  if (status === "loading") {
    /**
     * Session is being fetched
     */
    return <div>Loading...</div>;
  }

  if (status === "unauthenticated") {
    router.push("/login");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Med App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className={styles.button} onClick={signOut}>
        Log out
      </button>
      {/* <ImagesBlock /> */}
    </div>
  )
}



