import React from "react";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

import Head from 'next/head';
import { Header } from "../components/header";
import { ImagesBlock } from "../components/imageBlock";
import {ContainerDiv} from "../styles/componentStyle";


export default function Home() {
  const { data, status } = useSession();
  const router = useRouter();

  if (status === "loading") {
    /**
     * Session is being fetched
     */
    return <div>Loading...</div>;
  }

  if (status === "unauthenticated") {
    router.push("/login");
  }

  return (
    <ContainerDiv>
      <Head>
        <title>Med App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ImagesBlock />
    </ContainerDiv>
  )
}



