import React from "react";
/**
 * This is the home page
 * @return {JSX.Element}: The JSX code for home page.
 */

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {ImagesBlock} from "../components/imageBlock";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Med App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImagesBlock />
    </div>
  )
}



